DROP TABLE IF EXISTS Team5_TYPING_TBL;
CREATE TABLE Team5_TYPING_TBL(
	TYPING_ID INT AUTO_INCREMENT,
	TYPING_BODY VARCHAR(30),
	PRIMARY KEY(TYPING_ID)
	);
	
DROP TABLE IF EXISTS Team5_LOGIN_TBL;
	CREATE TABLE Team5_LOGIN_TBL(
	LOGIN_ID VARCHAR(20),
	PASS_WORD VARCHAR(20),
	PRIMARY KEY(LOGIN_ID)
	);
	

	